version: 0.2

phases:
  pre_build:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3.8 get-pip.py --user
      - pip3 install -r requirements.txt
  build:
    commands:
      - pytest
